/**
 * @brief Defines default random number generator and other constants
 *
 * @file Constants.cc
 * @author Mark Fornace
 * @date 2018-05-31
 */
#include <nupack/common/Threading.h>
#include <nupack/model/Constants.h>
#include <nupack/common/Random.h>
#include <nupack/common/Error.h>
#include <nupack/common/Costs.h>

#include <nupack/reflect/Print.h>
#include <nupack/reflect/Serialize.h>

#include <nupack/Version.h>
#include <nupack/types/Matrix.h>

#include <boost/archive/iterators/binary_from_base64.hpp>
#include <boost/archive/iterators/base64_from_binary.hpp>
#include <boost/archive/iterators/transform_width.hpp>
#include <boost/algorithm/string.hpp>

namespace nupack {

thread_local SharedMode GlobalSharedMode = SharedMode::copy;
thread_local std::vector<std::pair<void const *, nlohmann::json>> GlobalSharedState;

/// This may be used to turn knobs in development code without recompiling completely
string HackHelper = "";

/******************************************************************************************/

std::random_device StaticRandomDevice;

#ifndef NUPACK_RANDOM_DEVICE
#   error("NUPACK_RANDOM_DEVICE should be defined")
#elif NUPACK_RANDOM_DEVICE
    bool const RandomDevice = (arma::arma_rng::set_seed_random(), true);
    thread_local std::seed_seq SeedSequence{StaticRandomDevice(), StaticRandomDevice(), StaticRandomDevice(), StaticRandomDevice(),
                                            StaticRandomDevice(), StaticRandomDevice(), StaticRandomDevice(), StaticRandomDevice()};
    thread_local DefaultRNG StaticRNG{SeedSequence};
#else
    bool const RandomDevice = false;
    thread_local DefaultRNG StaticRNG{};
#endif

/******************************************************************************************/

std::string ReferenceSequence = "TTCCGTAGCGGAGGTCTATGTCCTCAATGTTTCGCGTCGTATTTATTTGCAAACAGATACGCATTCCCCCCCTGCCTTCCGAGCTGTTGCTACTTCACCAACTCGCGCTTAATGCATGAAACTCTAGTTCACTCACCGATTAGTTATCGATTAAGAAGAGACCAGTTGGGAATTAGCTAACCGCAACAAGAACGACCATATAGAGTTGTCTCCTAGTCTCAGCATTTGGCGAGGTTCAGTCCTTATTGCACGCTGGACCAAACGTCTCCTTGTCTACTAAAAATTCAATGGACTATGAGGAGCTCGTATAGAAGCTCGAATGGGTGCTCTATCCTCCGACTGTTTGAAAACATATGAAGACCAACGGTAATACACACGGTATCTACTTCAAGAAGCTGTGTTTGCCGAGCTCGACGATGTCACTGGCCGGTCCGGTGTGTACACCTATAGGGGGATTTGGTGTCCCCTTGTAGAAGCTAAGTTACCTGTTTGGCTATTAGCGTCGTGTGTAATGTTAATCTGCGATACTTATGAAATCGCATTGGTTTGCAGTTTCTCTACGCTGGTGTAGGACCGAGATAAAGTCGTGCGATAGTTATATAAGTACGAGAGTCAGAGCGCCGTTCAATAAGGTCCCGTGCCGTCCCCCCGTTGTTGCTGTCTCCTTGCGAAATGGATGATGACCAGGTTGGATAGAGAGCGCGACTTCTCGCTGGCTCGGTGATCGCTCGAGACTAGGACAACGGGGGCTATTGAGTGGACCTGACTACTATCCTATTGTCAGAAATGGCCACCTACACGCCTAACTGACTGGACGTTCGTAGTTGATCTGTTAAAACGAGAACTAGCACACTCAACGGCGTGGGGGCTAGTCTTAGGAAAAGTTTGGAGAAGAAAGAAGACCAACGGAACCCATCGATTTGAATTGACGTTGGTGTCTTTTCGTACAAGACAGAGGCAAAATTATTTTGCTTACTTCGTCATACAAAATCATTATCCCTTGACCTGCGGCCCCGCGTAACACCACCTCTCTGATAAGTAGGTTGACTATTCAGGGGGTCCACGAGCTACACGATCGTGCTCAAGAATTCCTTCCGGAATTGACGCGTAATCAACAAAAACCGATATTAGGACGGGCCTGAGTAAGATAGTTGTAGGTGTCCACGGTCTAGTTAGGGTGGTGGGTCCGAGTTCGCGTTACTTTGTTCTGTCAAACTCGGCCTGTGTGCCGAGATAAAGGCCACGATCGTTATATCATGCCAAGCGTCGACAGTCGGAAGGAACGCAATCCGACCGTTCGACCCGTGACCCGTGCCATAAGGACAAACATCGAACATTATTTGCGGGAAAATTCCTACGAAGCGTCGCGCTTCGCAGGAGTGTACTAACTATGTAAGGGAAACCTTACCACAGCTCGCATAGCTGTTTTCAGCTGGTGTGTTCATTTCAAGCGGTAGGTGATTTTCAGATAGTGGCGCGGCCCTGCGGATGCGTTGGTGCTAACACCCTCTATCGACGGGTATGGGTAGGATTGAAACCCTGCTGTATGTGTTAGATATCGATGCCGACTGGAGCTCGGCCATGCTTCGTATAAATTGTTCGATTCGTCACGGGGGGCCCAAGAAATATGGCAAATACACAAATCGGGGTTATCGTGTTTGATTCGACCATCTCCTACCGGCACAATACACATTTTTACGGTTACATTACTCACTGCGTGAACTGACTGGAATCGTCTCTTGTTGGCCCATCACAAAAGCTTTGCGTAAGGCTGTATGAATGCTTTACGTTTCTGGCTGATACTGCTTAGGGGCCGATTATCTAGAGGAATTAACACCCACCGTGTTGTCCGGAGGGTGCGCCGAGTTCCGATTAGACTAAGAAAGCGTGGTCGGATATAGGCAATATCGGTGCCCAGTTCACCTGCTGGATCTCTTGCCCGTGCGCAACGCGGTGATACTTTGATTGATCCTTGATCGTAATCCGTGACCTGGAAGATGTACTCTTACAAACACGCACTGAACCCGGCGTCGCTCTCGAGCGGTGTAGGAAATCTCTATTTCCCCTGTGCTTGTGTCTGTAGATTACCTTACACGTTTTACTGTATGATGCGCATGCCTTTTCGAGGTACCCCGGGCTTGGAACGTAGTGGGGAGCGGGTTGACTTTTCATCTAATCAACCGCTAGGTATTACCACTAAAGGATCATCCAATTAACATCATTTCGGCATTCACCAAATTGTTTGGGTGAGTGATCTCTAGACTAATGTACTGACTAAATCAATCTACATGGGTCTCCAAAAGTGTTCCGTGGTACCCCTACTACCACCCTCCGACCTTGATGGAATAGTAGCGGGAGTCTGGAGTTGATGGGACACAGCATTCCTGGATGGAACAAAATCCGGTCGAACTGGCACGAGCTTAACAATCATACGCATCGACGCGGATAATCGCGGGTTGTTCGTACCAACTAATGCCTTATAAAGAAGCCACGGCAGATGTGACTAGACAGCAACTAGTGAGGTGTGCAGCAGAGCGCCAACACGTTACCAGAGCGAACGTATTAATATAATTATTCATGCTATAACAGTCGCCAACTAGTCTACACATGGAGGCACCTGTGGTGGGGCCATTTAATGCACATGTGGCCGATTGCACAAAGATGGGGCAGACTATCTCAAGTCGGATCGCTATTTATTCTCCTTCACTAAGCCGACAAGCTTATATTAAATCGCCACACTACAACGTAACTGTGGAATACAGCCTGGGTCACTACAGTAGTTGTCTCTTCAGCGGCGATACATAGAGGCATGAGCAATGTAGACGTTGCAAGCCTCAGCATGAAAGACGCTGATTATAAATCTCCCAGAAATTTTCAAGCTTAGTTGCCACATAGCTCGGCTTTTCTAATTATCTCCTCTCCGGCTTCACGTGTGCCGCCCCCAGCATTAAGTTCTTACCCCCATTGAAACGATCCGTCATGTCAATTTGAGTTATCGGC";

string reference_dna(std::size_t length) {
    if (length > ReferenceSequence.size()) throw std::out_of_range("reference_dna");
    return ReferenceSequence.substr(0, length);
}

/******************************************************************************************/

std::string encode64(std::string_view val) {
    using namespace boost::archive::iterators;
    using It = base64_from_binary<transform_width<std::string_view::const_iterator, 6, 8>>;
    return {It(val.begin()), It(val.end())};
}

std::string decode64(std::string_view val) {
    using namespace boost::archive::iterators;
    using It = transform_width<binary_from_base64<std::string_view::const_iterator>, 8, 6>;
    return {It(val.begin()), It(val.end())};
}


}
